name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: false

      - name: Prerequisites
        uses: actions/setup-node@v4
        with:
          version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Building vibes
        run: npm run build:www

      - name: Deploying game to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/www
          cname: vibes.pixelheart.io
